apply plugin: 'com.android.application'
apply plugin: "com.jaredsburrows.license"

buildscript {
    repositories {
        mavenCentral()
        google()
        maven { url 'https://jitpack.io' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.1'
        classpath "com.jaredsburrows:gradle-license-plugin:0.9.3"
    }
}

android {
    defaultConfig {
        applicationId "de.idnow"
        minSdkVersion 28
        compileSdkVersion 36
        targetSdkVersion 36
        versionCode 170
        versionName "9.7.8"
        ndk.abiFilters 'armeabi-v7a','arm64-v8a'
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

}

allprojects {
    repositories {
        google()
        maven { url 'https://jitpack.io' }
        maven {
            url = uri("https://repo.authada.de/public/")
            authentication {
                basic(BasicAuthentication)
            }
            //Ask for credentials
            credentials {
                username ""
                password ""
            }
        }
        maven {
            url "https://raw.githubusercontent.com/idnow/de.idnow.android/master"
        }
    }
}

dependencies {
    implementation 'de.idnow.sdk:idnow-android-sdk:9.7.8'
    implementation 'de.idnow.android.eid:idnow-android-eid-sdk:3.5.4'
    implementation ("org.bouncycastle:bcprov-jdk15to18:1.83")
    implementation ("org.bouncycastle:bctls-jdk15to18:1.83")
    implementation ("org.bouncycastle:bcutil-jdk15to18:1.83")
}

android {

    packagingOptions {
        resources {
            excludes += ['META-INF/proguard/okhttp3.pro', 'META-INF/*.kotlin_module', 'META-INF/DEPENDENCIES.txt', 'META-INF/LICENSE.txt', 'META-INF/NOTICE.txt', 'META-INF/NOTICE', 'META-INF/LICENSE', 'META-INF/DEPENDENCIES', 'META-INF/notice.txt', 'META-INF/license.txt', 'META-INF/dependencies.txt', 'META-INF/LGPL2.1', 'META-INF/*.kotlin_module', 'META-INF/proguard/androidx-annotations.pro']
        }
    }
    namespace 'de.idnow'
    lint {
        abortOnError false
    }
}
